spring:
  profiles:
    include: secret

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  datasource:
    url: jdbc:h2:mem:~/redis
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
